apply from: "../../utils/android/resolveNodeModule.gradle"

rootProject.name = 'EsbuildExample'

def reactNativePath = resolveNodeModule('react-native', rootDir)
def cliPlatformAndroidPath = resolveNodeModule('@react-native-community/cli-platform-android', reactNativePath)
def gradlePluginPath = resolveNodeModule("@react-native/gradle-plugin", reactNativePath)

apply from: new File(cliPlatformAndroidPath, "native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':app'
includeBuild(gradlePluginPath)

if (settings.hasProperty("newArchEnabled") && settings.newArchEnabled == "true") {
    def reactAndroidPath = new File(reactNativePath, 'ReactAndroid')
    def hermesEnginePath = new File(reactAndroidPath, 'hermes-engine')
    
    include(":ReactAndroid")
    project(":ReactAndroid").projectDir = reactAndroidPath
    include(":ReactAndroid:hermes-engine")
    project(":ReactAndroid:hermes-engine").projectDir = hermesEnginePath
}
